"""
Page 6: Alerts & Safety Warnings — review active and past safety alerts.
"""
import streamlit as st
import requests
import pandas as pd

st.set_page_config(page_title="Alerts — Drone DSS", page_icon="🚨", layout="wide")

API = "http://localhost:8000"

st.markdown("# 🚨 Alerts & Safety Warnings")
st.markdown("Review all safety alerts generated by the decision engine.")
st.markdown("---")

# ── Fetch alerts ──
try:
    alerts = requests.get(f"{API}/decisions/alerts").json()
except Exception:
    st.error("⚠️ Cannot connect to the backend API.")
    st.stop()

# ── Severity filter ──
severity_filter = st.multiselect(
    "Filter by Severity",
    ["Info", "Warning", "Critical"],
    default=["Info", "Warning", "Critical"],
)

filtered = [a for a in alerts if a.get("severity") in severity_filter]

SEVERITY_ICON = {
    "Info": "ℹ️",
    "Warning": "⚠️",
    "Critical": "🔴",
}

SEVERITY_COLOR = {
    "Info": "#3b82f6",
    "Warning": "#f59e0b",
    "Critical": "#ef4444",
}

if filtered:
    # ── Severity counts ──
    sc1, sc2, sc3 = st.columns(3)
    info_count = len([a for a in filtered if a["severity"] == "Info"])
    warn_count = len([a for a in filtered if a["severity"] == "Warning"])
    crit_count = len([a for a in filtered if a["severity"] == "Critical"])
    sc1.metric("ℹ️ Info", info_count)
    sc2.metric("⚠️ Warning", warn_count)
    sc3.metric("🔴 Critical", crit_count)

    st.markdown("---")

    # ── Alert list ──
    for alert in filtered:
        icon = SEVERITY_ICON.get(alert["severity"], "ℹ️")
        color = SEVERITY_COLOR.get(alert["severity"], "#3b82f6")
        mission = alert.get("mission_id", "—")
        timestamp = str(alert.get("created_at", ""))[:19] if alert.get("created_at") else "—"
        rule = alert.get("rule_triggered", "")

        st.markdown(f"""
        <div style="background: rgba(30,41,59,0.7); border-left: 4px solid {color}; border-radius: 8px; padding: 16px; margin: 8px 0;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <span style="font-size: 1.1rem; font-weight: 600; color: #e2e8f0;">{icon} {alert['severity']}</span>
                <span style="color: #94a3b8; font-size: 0.85rem;">{timestamp}</span>
            </div>
            <p style="color: #cbd5e1; margin: 8px 0 4px 0;">{alert['description']}</p>
            <p style="color: #64748b; font-size: 0.8rem; margin: 0;">Mission: {mission} {('| Rule: ' + rule) if rule else ''}</p>
        </div>
        """, unsafe_allow_html=True)
else:
    st.success("✅ No safety alerts. All operations are within safe thresholds.")
